//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testWCF.CustomerAccessWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.clarica.com", ConfigurationName="CustomerAccessWS.IIndividualClientWS")]
    public interface IIndividualClientWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.clarica.com/IIndividualClientWS/InitializeCA", ReplyAction="http://www.clarica.com/IIndividualClientWS/InitializeCAResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ServiceResult")]
        testWCF.CustomerAccessWS.InitializeCustomerAccessDataResponse InitializeCA(testWCF.CustomerAccessWS.InitializeCustomerAccessDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.clarica.com/IIndividualClientWS/InitializeCA", ReplyAction="http://www.clarica.com/IIndividualClientWS/InitializeCAResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ServiceResult")]
        System.Threading.Tasks.Task<testWCF.CustomerAccessWS.InitializeCustomerAccessDataResponse> InitializeCAAsync(testWCF.CustomerAccessWS.InitializeCustomerAccessDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.clarica.com/IIndividualClientWS/GetDataWithSession", ReplyAction="http://www.clarica.com/IIndividualClientWS/GetDataWithSessionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        testWCF.CustomerAccessWS.GetDataWithSessionResponse GetDataWithSession(testWCF.CustomerAccessWS.GetDataWithSessionRequest arguments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.clarica.com/IIndividualClientWS/GetDataWithSession", ReplyAction="http://www.clarica.com/IIndividualClientWS/GetDataWithSessionResponse")]
        System.Threading.Tasks.Task<testWCF.CustomerAccessWS.GetDataWithSessionResponse> GetDataWithSessionAsync(testWCF.CustomerAccessWS.GetDataWithSessionRequest arguments);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.clarica.com")]
    public partial class InitializeCustomerAccessDataRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InitializeCustomerAccessDataRequestArguments initializeCustomerDataRequestHeaderField;
        
        private InitializeCustomerDataRequestBody initializeCustomerDataRequestBodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InitializeCustomerAccessDataRequestArguments initializeCustomerDataRequestHeader {
            get {
                return this.initializeCustomerDataRequestHeaderField;
            }
            set {
                this.initializeCustomerDataRequestHeaderField = value;
                this.RaisePropertyChanged("initializeCustomerDataRequestHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public InitializeCustomerDataRequestBody initializeCustomerDataRequestBody {
            get {
                return this.initializeCustomerDataRequestBodyField;
            }
            set {
                this.initializeCustomerDataRequestBodyField = value;
                this.RaisePropertyChanged("initializeCustomerDataRequestBody");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.clarica.com")]
    public partial class InitializeCustomerAccessDataRequestArguments : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accessIdField;
        
        private string applicationVersionField;
        
        private string authenticationTokenField;
        
        private string contextField;
        
        private object customAuthenticationReturnField;
        
        private string domainField;
        
        private string languageField;
        
        private string requesterField;
        
        private string serviceNameField;
        
        private string sessionIdField;
        
        private string sessionKeyField;
        
        private string traceLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccessId {
            get {
                return this.accessIdField;
            }
            set {
                this.accessIdField = value;
                this.RaisePropertyChanged("AccessId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ApplicationVersion {
            get {
                return this.applicationVersionField;
            }
            set {
                this.applicationVersionField = value;
                this.RaisePropertyChanged("ApplicationVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AuthenticationToken {
            get {
                return this.authenticationTokenField;
            }
            set {
                this.authenticationTokenField = value;
                this.RaisePropertyChanged("AuthenticationToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("Context");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public object CustomAuthenticationReturn {
            get {
                return this.customAuthenticationReturnField;
            }
            set {
                this.customAuthenticationReturnField = value;
                this.RaisePropertyChanged("CustomAuthenticationReturn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
                this.RaisePropertyChanged("Domain");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Requester {
            get {
                return this.requesterField;
            }
            set {
                this.requesterField = value;
                this.RaisePropertyChanged("Requester");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
                this.RaisePropertyChanged("ServiceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
                this.RaisePropertyChanged("SessionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string SessionKey {
            get {
                return this.sessionKeyField;
            }
            set {
                this.sessionKeyField = value;
                this.RaisePropertyChanged("SessionKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string TraceLevel {
            get {
                return this.traceLevelField;
            }
            set {
                this.traceLevelField = value;
                this.RaisePropertyChanged("TraceLevel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.clarica.com")]
    public partial class TaxRegInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string subSectionField;
        
        private string friendlyNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SubSection {
            get {
                return this.subSectionField;
            }
            set {
                this.subSectionField = value;
                this.RaisePropertyChanged("SubSection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FriendlyName {
            get {
                return this.friendlyNameField;
            }
            set {
                this.friendlyNameField = value;
                this.RaisePropertyChanged("FriendlyName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.clarica.com")]
    public partial class ProductInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sectionField;
        
        private string subSectionField;
        
        private string customerFriendlyNameField;
        
        private string contractNumberLinkField;
        
        private string docCentreDisplayFlagField;
        
        private string sLFBrandFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Section {
            get {
                return this.sectionField;
            }
            set {
                this.sectionField = value;
                this.RaisePropertyChanged("Section");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SubSection {
            get {
                return this.subSectionField;
            }
            set {
                this.subSectionField = value;
                this.RaisePropertyChanged("SubSection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CustomerFriendlyName {
            get {
                return this.customerFriendlyNameField;
            }
            set {
                this.customerFriendlyNameField = value;
                this.RaisePropertyChanged("CustomerFriendlyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ContractNumberLink {
            get {
                return this.contractNumberLinkField;
            }
            set {
                this.contractNumberLinkField = value;
                this.RaisePropertyChanged("ContractNumberLink");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string docCentreDisplayFlag {
            get {
                return this.docCentreDisplayFlagField;
            }
            set {
                this.docCentreDisplayFlagField = value;
                this.RaisePropertyChanged("docCentreDisplayFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SLFBrandFlag {
            get {
                return this.sLFBrandFlagField;
            }
            set {
                this.sLFBrandFlagField = value;
                this.RaisePropertyChanged("SLFBrandFlag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.clarica.com")]
    public partial class ContractInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string systemOfRecordIdField;
        
        private string contractNumberField;
        
        private string productIdField;
        
        private string taxRegistrationTypeField;
        
        private string advisorIdField;
        
        private ProductInfo productInfoField;
        
        private TaxRegInfo taxRegInfoField;
        
        private string spousalIndicatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SystemOfRecordId {
            get {
                return this.systemOfRecordIdField;
            }
            set {
                this.systemOfRecordIdField = value;
                this.RaisePropertyChanged("SystemOfRecordId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ContractNumber {
            get {
                return this.contractNumberField;
            }
            set {
                this.contractNumberField = value;
                this.RaisePropertyChanged("ContractNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("ProductId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TaxRegistrationType {
            get {
                return this.taxRegistrationTypeField;
            }
            set {
                this.taxRegistrationTypeField = value;
                this.RaisePropertyChanged("TaxRegistrationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AdvisorId {
            get {
                return this.advisorIdField;
            }
            set {
                this.advisorIdField = value;
                this.RaisePropertyChanged("AdvisorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public ProductInfo ProductInfo {
            get {
                return this.productInfoField;
            }
            set {
                this.productInfoField = value;
                this.RaisePropertyChanged("ProductInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public TaxRegInfo TaxRegInfo {
            get {
                return this.taxRegInfoField;
            }
            set {
                this.taxRegInfoField = value;
                this.RaisePropertyChanged("TaxRegInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SpousalIndicator {
            get {
                return this.spousalIndicatorField;
            }
            set {
                this.spousalIndicatorField = value;
                this.RaisePropertyChanged("SpousalIndicator");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.clarica.com")]
    public partial class GetDataWithSessionResponseBody : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ContractInfo[] contractInfoField;
        
        private string clClientNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContractInfo", Order=0)]
        public ContractInfo[] ContractInfo {
            get {
                return this.contractInfoField;
            }
            set {
                this.contractInfoField = value;
                this.RaisePropertyChanged("ContractInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ClClientNumber {
            get {
                return this.clClientNumberField;
            }
            set {
                this.clClientNumberField = value;
                this.RaisePropertyChanged("ClClientNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.clarica.com")]
    public partial class GetDataWithSessionResponseHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string applicationVersionField;
        
        private string serviceNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ApplicationVersion {
            get {
                return this.applicationVersionField;
            }
            set {
                this.applicationVersionField = value;
                this.RaisePropertyChanged("ApplicationVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
                this.RaisePropertyChanged("ServiceName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.clarica.com")]
    public partial class GetDataWithSessionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GetDataWithSessionResponseHeader getDataWithSessionResponseHeaderField;
        
        private Result getDataWithSessionResponseStatusField;
        
        private GetDataWithSessionResponseBody getDataWithSessionResponseBodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public GetDataWithSessionResponseHeader getDataWithSessionResponseHeader {
            get {
                return this.getDataWithSessionResponseHeaderField;
            }
            set {
                this.getDataWithSessionResponseHeaderField = value;
                this.RaisePropertyChanged("getDataWithSessionResponseHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Result getDataWithSessionResponseStatus {
            get {
                return this.getDataWithSessionResponseStatusField;
            }
            set {
                this.getDataWithSessionResponseStatusField = value;
                this.RaisePropertyChanged("getDataWithSessionResponseStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public GetDataWithSessionResponseBody getDataWithSessionResponseBody {
            get {
                return this.getDataWithSessionResponseBodyField;
            }
            set {
                this.getDataWithSessionResponseBodyField = value;
                this.RaisePropertyChanged("getDataWithSessionResponseBody");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.clarica.com")]
    public partial class Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ReturnCodes returnCodeField;
        
        private System.DateTime startTimeField;
        
        private System.DateTime endTimeField;
        
        private ResultMessage[] resultMessageField;
        
        private long messageCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ReturnCodes ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("ReturnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("StartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("EndTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public ResultMessage[] ResultMessage {
            get {
                return this.resultMessageField;
            }
            set {
                this.resultMessageField = value;
                this.RaisePropertyChanged("ResultMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long MessageCount {
            get {
                return this.messageCountField;
            }
            set {
                this.messageCountField = value;
                this.RaisePropertyChanged("MessageCount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.clarica.com")]
    public enum ReturnCodes {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Error,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.clarica.com")]
    public partial class ResultMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageCodeField;
        
        private string messageSeverityField;
        
        private string messageInformationField;
        
        private string messageDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MessageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
                this.RaisePropertyChanged("MessageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MessageSeverity {
            get {
                return this.messageSeverityField;
            }
            set {
                this.messageSeverityField = value;
                this.RaisePropertyChanged("MessageSeverity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MessageInformation {
            get {
                return this.messageInformationField;
            }
            set {
                this.messageInformationField = value;
                this.RaisePropertyChanged("MessageInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MessageDescription {
            get {
                return this.messageDescriptionField;
            }
            set {
                this.messageDescriptionField = value;
                this.RaisePropertyChanged("MessageDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.clarica.com")]
    public partial class GetDataWithSessionRequestBody : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object requestClassField;
        
        private bool contractInfoRequiredField;
        
        private string clientIdOnCXSystemField;
        
        private string advisorIdField;
        
        private bool supportToolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public object RequestClass {
            get {
                return this.requestClassField;
            }
            set {
                this.requestClassField = value;
                this.RaisePropertyChanged("RequestClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool ContractInfoRequired {
            get {
                return this.contractInfoRequiredField;
            }
            set {
                this.contractInfoRequiredField = value;
                this.RaisePropertyChanged("ContractInfoRequired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ClientIdOnCXSystem {
            get {
                return this.clientIdOnCXSystemField;
            }
            set {
                this.clientIdOnCXSystemField = value;
                this.RaisePropertyChanged("ClientIdOnCXSystem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AdvisorId {
            get {
                return this.advisorIdField;
            }
            set {
                this.advisorIdField = value;
                this.RaisePropertyChanged("AdvisorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool SupportTool {
            get {
                return this.supportToolField;
            }
            set {
                this.supportToolField = value;
                this.RaisePropertyChanged("SupportTool");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.clarica.com")]
    public partial class GetDataWithSessionRequestArguments : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accessIdField;
        
        private string applicationVersionField;
        
        private string authenticationTokenField;
        
        private string contextField;
        
        private object customAuthenticationReturnField;
        
        private string domainField;
        
        private string languageField;
        
        private string requesterField;
        
        private string serviceNameField;
        
        private string sessionIdField;
        
        private string traceLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccessId {
            get {
                return this.accessIdField;
            }
            set {
                this.accessIdField = value;
                this.RaisePropertyChanged("AccessId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ApplicationVersion {
            get {
                return this.applicationVersionField;
            }
            set {
                this.applicationVersionField = value;
                this.RaisePropertyChanged("ApplicationVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AuthenticationToken {
            get {
                return this.authenticationTokenField;
            }
            set {
                this.authenticationTokenField = value;
                this.RaisePropertyChanged("AuthenticationToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("Context");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public object CustomAuthenticationReturn {
            get {
                return this.customAuthenticationReturnField;
            }
            set {
                this.customAuthenticationReturnField = value;
                this.RaisePropertyChanged("CustomAuthenticationReturn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
                this.RaisePropertyChanged("Domain");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Requester {
            get {
                return this.requesterField;
            }
            set {
                this.requesterField = value;
                this.RaisePropertyChanged("Requester");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
                this.RaisePropertyChanged("ServiceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
                this.RaisePropertyChanged("SessionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string TraceLevel {
            get {
                return this.traceLevelField;
            }
            set {
                this.traceLevelField = value;
                this.RaisePropertyChanged("TraceLevel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.clarica.com")]
    public partial class GetDataWithSessionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GetDataWithSessionRequestArguments getDataWithSessionRequestHeaderField;
        
        private GetDataWithSessionRequestBody getDataWithSessionRequestBodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public GetDataWithSessionRequestArguments GetDataWithSessionRequestHeader {
            get {
                return this.getDataWithSessionRequestHeaderField;
            }
            set {
                this.getDataWithSessionRequestHeaderField = value;
                this.RaisePropertyChanged("GetDataWithSessionRequestHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public GetDataWithSessionRequestBody GetDataWithSessionRequestBody {
            get {
                return this.getDataWithSessionRequestBodyField;
            }
            set {
                this.getDataWithSessionRequestBodyField = value;
                this.RaisePropertyChanged("GetDataWithSessionRequestBody");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.clarica.com")]
    public partial class InitializeCustomerAccessDataResponseHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string applicationVersionField;
        
        private string serviceNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ApplicationVersion {
            get {
                return this.applicationVersionField;
            }
            set {
                this.applicationVersionField = value;
                this.RaisePropertyChanged("ApplicationVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
                this.RaisePropertyChanged("ServiceName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.clarica.com")]
    public partial class InitializeCustomerAccessDataResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InitializeCustomerAccessDataResponseHeader initializeCustomerAccessDataResponseHeaderField;
        
        private Result initializeCustomerAccessDataResponseStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InitializeCustomerAccessDataResponseHeader initializeCustomerAccessDataResponseHeader {
            get {
                return this.initializeCustomerAccessDataResponseHeaderField;
            }
            set {
                this.initializeCustomerAccessDataResponseHeaderField = value;
                this.RaisePropertyChanged("initializeCustomerAccessDataResponseHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Result initializeCustomerAccessDataResponseStatus {
            get {
                return this.initializeCustomerAccessDataResponseStatusField;
            }
            set {
                this.initializeCustomerAccessDataResponseStatusField = value;
                this.RaisePropertyChanged("initializeCustomerAccessDataResponseStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.clarica.com")]
    public partial class InitializeCustomerDataRequestBody : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string signinSiteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SigninSite {
            get {
                return this.signinSiteField;
            }
            set {
                this.signinSiteField = value;
                this.RaisePropertyChanged("SigninSite");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIndividualClientWSChannel : testWCF.CustomerAccessWS.IIndividualClientWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IndividualClientWSClient : System.ServiceModel.ClientBase<testWCF.CustomerAccessWS.IIndividualClientWS>, testWCF.CustomerAccessWS.IIndividualClientWS {
        
        public IndividualClientWSClient() {
        }
        
        public IndividualClientWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IndividualClientWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndividualClientWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndividualClientWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public testWCF.CustomerAccessWS.InitializeCustomerAccessDataResponse InitializeCA(testWCF.CustomerAccessWS.InitializeCustomerAccessDataRequest request) {
            return base.Channel.InitializeCA(request);
        }
        
        public System.Threading.Tasks.Task<testWCF.CustomerAccessWS.InitializeCustomerAccessDataResponse> InitializeCAAsync(testWCF.CustomerAccessWS.InitializeCustomerAccessDataRequest request) {
            return base.Channel.InitializeCAAsync(request);
        }
        
        public testWCF.CustomerAccessWS.GetDataWithSessionResponse GetDataWithSession(testWCF.CustomerAccessWS.GetDataWithSessionRequest arguments) {
            return base.Channel.GetDataWithSession(arguments);
        }
        
        public System.Threading.Tasks.Task<testWCF.CustomerAccessWS.GetDataWithSessionResponse> GetDataWithSessionAsync(testWCF.CustomerAccessWS.GetDataWithSessionRequest arguments) {
            return base.Channel.GetDataWithSessionAsync(arguments);
        }
    }
}
